# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YoutubeMusic' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YoutubeMusic
  pod 'MobileCenter', '~> 0.10.1'
  pod 'RNMobileCenterShared', '~> 0.7.0'

  

  target 'YoutubeMusicTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'YoutubeMusic-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YoutubeMusic-tvOS

  target 'YoutubeMusic-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
